export const CHANGE_CATEGORY="CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS"

export const GET_MOVIE_SUCCESS="GET_MOVIE_SUCCESS"
export const CHANGE_MOVIE="CHANGE_MOVIE"

export const GET_POPULAR_SUCCESS="GET_POPULAR_SUCCESS"

export const GET_SIMILAR_SUCCESS="GET_SIMILAR_SUCCESS"

export const GET_MOVIE_DETAIL_SUCCESS="GET_MOVIE_DETAIL_SUCCESS"

export const GET_MOVIE_CHANGE_SUCCESS="GET_MOVIE_CHANGE_SUCCESS"

export const GET_MOVIE_TRAILER_SUCCESS="GET_MOVIE_TRAILER_SUCCESS"

export const GET_SEARCH_SUCCESS="GET_SEARCH_SUCCESS"

export const GET_SHOW_CATEGORIES_SUCCESS="GET_SHOW_CATEGORIES_SUCCESS"
export const GET_SHOW_SUCCESS="GET_SHOW_SUCCESS"
export const GET_SHOW_SIMILAR_SUCCESS="GET_SHOW_SIMILAR_SUCCESS"
export const GET_SHOW_CHANGE_SUCCESS="GET_SHOW_CHANGE_SUCCESS"
export const GET_SHOW_DETAIL_SUCCESS="GET_SHOW_DETAIL_SUCCESS"
export const CHANGE_SHOW="CHANGE_SHOW"
export const GET_SHOW_TRAILER_SUCCESS="GET_SHOW_TRAILER_SUCCESS"
export const GET_SHOW_POPULAR_SUCCESS="GET_SHOW_POPULAR_SUCCESS"



export const GET_USER_DETAIL_SUCCESS="GET_USER_DETAIL_SUCCESS"
export const POST_USER_REGISTER_SUCCESS="POST_USER_REGISTER_SUCCESS"
export const POST_USER_LOGİN_SUCCESS="POST_USER_LOGİN_SUCCESS"




